version: 2.1
jobs:
 build:
   docker:
   - image: circleci/ruby:2.6.3-node
     environment:
       RAILS_ENV: test
   - image: circleci/mysql:8.0-ram
     environment:
       MYSQL_DATABASE: KANMAP_test
       MYSQL_ALLOW_EMPTY_PASSWORD: true
       MYSQL_ROOT_HOST: '%'
       MYSQL_PORT: 3306
       MYSQL_USER: root
   working_directory: ~/KANMAP
   steps:
   - checkout
   - restore_cache:
       keys:
       - v1-dependencies-{{ checksum "Gemfile.lock" }}
       - v1-dependencies-
   - run:
       name: install dependencies
       command: |
         gem install bundler -v 1.17.3
         bundle install --jobs=4 --retry=3 --path vendor/bundle
   - save_cache:
       paths:
       - ./vendor/bundle
       key: v1-dependencies-{{ checksum "Gemfile.lock" }}
   # Database setup
   - run:
       name: Prepare db
       command: |
         bundle exec rails db:schema:load --trace
   # run tests!
   - run:
       name: Run rspec
       command: |
         mkdir /tmp/test-results
         TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
         bundle exec rspec --format progress --color --format documentation

   # collect reports
   - store_test_results:
       path: /tmp/test-results
   - store_artifacts:
       path: /tmp/test-results
       destination: test-results