default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") %>
  socket: /tmp/mysql.sock
  host: db
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  # database: KANMAP_dc_development
  database: KANMAP_development


test:
  <<: *default
  database: KANMAP_test
  host: <%= ENV['MYSQL_ROOT_HOST'] || '127.0.0.1' %>

production:
  <<: *default
  database: KANMAP_production
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") %>
  socket: /var/run/mysqld/mysqld.sock
