default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") %>
  # socket: /tmp/mysql.sock
  
development:
  <<: *default
  database: KANMAP_development


test:
  <<: *default
  database: KANMAP_test
  host: <%= ENV['MYSQL_ROOT_HOST'] || '127.0.0.1' %>

production:
  <<: *default
  database: KANMAP_production
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
