default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  # database: KANMAP_dc_development
  database: KANMAP_development

test:
  <<: *default
  database: KANMAP_test
  host: <%= ENV['MYSQL_ROOT_HOST'] || '127.0.0.1' %>

production:
  <<: *default
  database: KANMAP_production
  username: root
  password: 136445yY$
  socket: /var/lib/mysql/mysql.sock
