default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 136445yY$
  socket: /tmp/mysql.sock
  
development:
  <<: *default
  # database: KANMAP_dc_development
  database: KANMAP_development
  # host: db

test:
  <<: *default
  database: KANMAP_test
  host: <%= ENV['MYSQL_ROOT_HOST'] || '127.0.0.1' %>

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: KANMAP_production
  username: root
  password: 136445yY$
  socket: /var/lib/mysql/mysql.sock